const campaigns = [
    {
        "cam":{
            "name": "vladimir",
            "category":"education",
            "campaignName":"Mototaxista Vladimir",
            "author": "Vladimir",
            "authorInitial": "V",
            "target":200,
            "title":{
                "en":"Help Vladimir Work As a Mototaxista",
                "sp":"Ayuda Vladimir trabajar Mototaxista"
                },
            "description":{
                "en": "Help Vladimir get back on his feet after his motorcycle was stolen",
                "sp": "Help Vladimir get back on his feet after his motorcycle was stolen but in spanish"
            },
            "date": "12/12/2020",
            "image": require('../../../pics/vlad1.jpg'),
            "images": [
                require('../../../pics/vlad2.jpg'),
                require('../../../pics/vlad3.jpg'),
                require('../../../pics/vlad4.jpg'),
            ],
            "headers": {
                "en":[
                    "Vladimir’s Story",
                    "Where I’ve come from…",
                    "Who I am today…",
                    "Where I’m going…"
                ],
                "sp":[
                    "La historia de vladimir",
                    "De dónde vengo",
                    "Quien soy hoy en día",
                    "Hacia dónde voy"
                ]
            },
            "story": {
                "en":[
                    "I’ve gotten it together since I got out of jail. I used to have everything I wanted but it was wrongfully obtained. I decided to work and fight to be able to have what I do starting over again on the right path. I have a disability in one leg and have always had a motorcycle that I use to support my family. In January someone stole it from me and I was left without any way of making money to support my family. We spent many nights going to bed hungry for up to two days at a time because I didn’t have food or money to feed them. I had good people that gave me a hand with the food, but what I really want is to work and keep fighting for my family. God watches over me and never abandons me. A few days ago a friend gifted me a new motorcycle that was his, but the papers were lost and he gave it to me so that I could work and help my family, but right now I haven’t been able to work because I don’t have the money to get new papers for the motorcycle or to buy oil and have it serviced so that it can run. I’m asking you to give me a hand so I can work and keep fighting for the beautiful family that father God has given me. With my motorcycle I can help a lot. I can help my daughters and drive them to their classes at college. I ask you with all my heart and promise that one day in life before I leave this world I will be so grateful to all of you. I’m hoping for your support for this great man that at one time made mistakes and committed a crime and paid for it in jail, but now is better, changed and improved, doing everything right that he can.",
                    "When I was little I lived with my mother, where the only thing I received was her abuse and the abuse of my father. They hit me a lot and treated me very badly. I watched how my father hit my mother and I without being able to do anything because I was little. The abuse was so bad from my parents that at six years old I went to live with my grandmother who loved me so much. She treated me so well. She helped me a lot and I started to study. I always wanted to be a merchant marine so I could travel and see the world. I kept going and behaved myself but at fourteen my grandmother passed away and my life fell apart. I was left alone without anyone’s help. At fourteen I entered the world of crime and at almost fifteen I killed my first man. At almost sixteen I killed the other. From there I started my life in the world of crime. It was so bad that when I came of age I was locked up twice in the jail Las Flores de Catia. It was a very dangerous jail, and there I got used to crime and kept getting deeper into that world. It was so bad that in the 90’s I was the second most wanted man in Venezuela. I was in all the newspapers and on TV. The police chief looking for me was named Iván Simonovis and he brought me to justice and I was sentenced to 13 years in prison where I went through eight jails throughout the country. In jail people still respected me and I was in the leadership of a prison gang. I continued to do bad things until one day I found God and he helped me get out of that life. My mother, my stepfather, my wife and my family supported me and visited me in all the jails that I went to. I always had the support of my family in that monster of cement where I learned evil but also learned good things. One night I decided to leave that world in which I was buried. I wanted to leave jail alive and achieved that thanks to God. I got out on the 16th of September, the day of Our Lady of Mercy, and also my wife Yamilet Zapata’s birthday. Finally I escaped that labyrinth where men feed themselves with the blood of living beings. Thanks to God I left that jail with my life.",
                    "After getting out of jail on September 16th, I arrived at my new home and started a new life. I left the world of drugs where I was buried for years. I’ve been out of the world of drugs and crime for 17 years. I started to work and get ahead to give a good life and education to my two daughters. I know that I was a bad person, but I want my daughters to be different than their father; educated and prepared women. Today I feel very blessed by God because my daughter, at 17 years old, has started to study at the Central University of Venezuela because she is a very good student. My younger daughter is 16 and in her senior year of high school. She graduates this year and is a very good student. My daughters have gotten ahead. I have taught them the right values that no one ever taught me. I am very proud of my family, of my daughters and my wife. I am a changed and tenacious man; I was able to get ahead and feel that I’m doing very well. I feel very good right now without being a criminal and without taking drugs: I feel very thankful to God and my family for supporting me all these years that I was buried in the world of crime. Here you have a new Vladimir, improved and moving forward. Many thanks to those who have supported me and those who have believed in my rehabilitation.",
                    "At 46 years old I feel very good because these days I work for the rights of those deprived of their freedom. Now I help people that find themselves in that world. It is never too late. A few months ago I applied for a program online to get my high school diploma and was selected. God always gives good opportunities. I will keep fighting and growing each day. A big hug with all my heart to all of you for believing in me and my family. God bless you."
                ],
                "sp": [
                    "Yo he salido adelante desde que salí de la cárcel. Antes tenía todo lo que yo quería pero era mal habido, pero yo decidí trabajar y luchar para poder tener mis cosas echándole pichón a la vida por el buen camino. Yo tengo una discapacidad en una pierna y bueno siempre he tenido moto y he trabajado con mi moto que es el sustento de mi familia. En enero me robaron la moto y quedé sin ninguna entrada de dinero para poder ayudar a mi familia, duramos muchas veces acostándonos sin comer hasta dos días porque no tenía alimentos ni dinero para poder darle alimentos a mi familia. Si conseguí buenas personas que me echaban una mano para los alimentos, pero yo lo que quiero es trabajar y seguir luchando por mi familia. Dios siempre va por delante y nunca me abandona. Hace varios días un amigo me regaló una moto que era de él, pero se le perdieron los papeles y él me la dió para que yo trabajara y ayude a mi familia, pero en este momento no he podido trabajar porque no tengo el dinero para sacarle los papeles a mi moto ni tengo para comprarle el aceite y hacerle el servicio que se lleva la moto. Se los pido de todo corazón, mi gente, que me echen una mano para trabajar y seguir luchando por la familia tan linda y bella que me dió papá Dios. Yo con mi moto me puedo ayudar mucho y ayudar a mis hijas y llevarlas a la universidad, se los pido de todo corazón y les prometo que alguna vez en la vida antes de yo parta de este mundo se los voy agradecer toda la vida y espero su aporte a este gran hombre que en algún momento cometió errores y cometió un delito y los pagó con cárcel, pero ahora está bien, cambiado y renovado, haciendo todo lo bueno.",
                    "Desde pequeño vivía con mi madre, donde lo único que recibí fue su maltrato y el de mi padre. Me golpeaban mucho y me trataban muy mal. Yo veía como mi padre golpeaba a mi madre y yo sin poder hacer nada porque era pequeño. Fue tanto el maltrato que recibí de mis padres que a  los 6 años me fuí a vivir con mi abuela que tanto me amó. Ella me trataba muy bien, me ayudó mucho y empecé a estudiar. Yo  siempre quise ser un marino mercante para viajar y conocer  partes del mundo. Yo seguía adelante y me portaba muy bien pero a la edad de los 14 años mi abuela falleció y mi vida se derrumbó.  Quedé solo sin apoyo de nadie. A la edad de los 14 años empecé en el mundo de la delincuencia y ya casi cumpliendo los 15 años maté al primer hombre y ya casi a los 16 años mate al otro. De ahí empezó mi vida en el mundo de la delincuencia. Fue tanto así que cuando cumplí la mayoría de edad estuve preso en dos oportunidades en la  cárcel Las Flores de Catia.  Era una cárcel muy peligrosa, y ahí me gradué de delincuente y seguí sonando en el mundo de la delincuencia. Fue tanto así que en los años 90 fuí el segundo hombre más buscado de Venezuela. Salía en todos los periódicos y en las noticias en la televisión. El comisario que me buscaba era Iván Simonovis, y bueno me puse a derecho con la justicia y fui condenado  a 13 años de prisión donde recorrí 8 cárceles del país. En la cárcel aún me seguían respetando y estuve jugando en el carro de los pranes como líder y ahí seguí haciendo lo malo, hasta que un día conocí a Dios y él me ayudó a salir de esa vida. Mi madre, mi padrastro, mi esposa y mis dos hijas  me apoyaban y me visitaban a todas la cárceles que era trasladado. Siempre tuve el apoyo de mi familia en ese monstruo de cemento donde aprendí lo malo y también aprendí cosas buenas. Una noche decidí salirme de ese mundo donde estaba sumergido y yo quería salir vivo de la cárcel y lo logré gracias a Dios. Salí un 16 de septiembre,  el día de las Mercedes y día del preso y también es el día que mi esposa Yamilet Zapata cumple años. Al fin salí de ese laberinto donde el humano se alimenta de sangre de seres vivos. Gracias a Dios  logré salir vivo de esa cárcel.",
                    "Desde que salí de la cárcel aquel 16 de septiembre, llegué a mi nuevo hogar y empecé una nueva vida. Dejé el mundo de las drogas donde estuve sumergido muchos años. Ya tengo 17 años que salí del mundo de las drogas y del mundo de la delincuencia, empecé a trabajar y a surgir para salir adelante y darle una buena vida y educación a mis dos hijas. Yo sé que yo era una persona mala, pero yo quería que mis hijas fueran diferentes a su papá; mujeres estudiadas y preparadas. Hoy en día me siento bendecido por Dios porque mi hija a los 17 años entró a estudiar en la Universidad Central de Venezuela, por ser muy buena estudiante. Mi hija pequeña tiene 16 años y está en quinto año de bachillerato.  Este año se gradúa y es muy buena estudiante. Mis hijas han salido adelante. Yo les he enseñado los buenos valores que a mi nunca me enseñaron. Me siento muy orgulloso de mi familia, de mis hijas y de mi esposa.Yo soy un hombre cambiado y luchador; logré salir adelante y siento que lo estoy haciendo muy bien. Me siento muy bien ahora sin ser un delincuente y sin consumir drogas: Me siento muy agradecido con Dios y mi familia por apoyarme tantos años que estuve sumergido en el mundo de la delincuencia. Aquí tienen a un Vladimir nuevo y renovado y echado p’alante. Muchas gracias a los que me han apoyado y los que han creído en mi reinserción social.",
                    "Ya a la edad de 46 años me siento muy bien porque hoy en día trabajo por los derechos de los privados de libertad. Ahora ayudo a la gente que se encuentra en ese mundo, pero nunca es tarde. Hace unos meses me postulé en un programa privado por internet, para sacar mi bachillerato y salí seleccionado. Siempre Dios le da buenas oportunidades a uno. Seguiré luchando y creciendo cada día más.Un fuerte abrazo de todo corazón a todos ustedes por creer en mí y en mi familia. Dios los bendiga.",
                ]
            }
        },
    },
    {
        "cam":{
            "name":"eduardo",
            "campaignName":"campaign",
            "target":400,
            "category":"healthcare",
            "author":"Eduardo",
            "authorInitial": "E",
            "title":{
                "en":"Help Eduardo",
                "sp":"Help Eduardo"
                },
            "description":{
                "en": "Help Eduardo get back on his feet after his motorcycle was stolen",
                "sp": "Help Eduardo get back on his feet after his motorcycle was stolen"
            },
            "date": "12 December 2020",
            "image": require('../../../pics/vlad2.jpg'),
            "images": [
                require('../../../pics/vlad1.jpg'),
                require('../../../pics/vlad1.jpg'),
                require('../../../pics/vlad1.jpg'),
                require('../../../pics/vlad1.jpg')
            ],
            "headers": {
                "en":[
                    "Vladimir’s Story",
                    "Where I’ve come from…",
                    "Who I am today…",
                    "Where I’m going…"
                ],
                "sp":[
                    "Vladimir’s StorySP",
                    "Where I’ve come from…",
                    "Who I am today…",
                    "Where I’m going…"
                ]
            },
            "story": {
                "en":[
                    "I’ve gotten it together since I got out of jail. I used to have everything I wanted but it was wrongfully obtained. I decided to work and fight to be able to have what I do starting over again on the right path. I have a disability in one leg and have always had a motorcycle that I use to support my family. In January someone stole it from me and I was left without any way of making money to support my family. We spent many nights going to bed hungry for up to two days at a time because I didn’t have food or money to feed them. I had good people that gave me a hand with the food, but what I really want is to work and keep fighting for my family. God watches over me and never abandons me. A few days ago a friend gifted me a new motorcycle that was his, but the papers were lost and he gave it to me so that I could work and help my family, but right now I haven’t been able to work because I don’t have the money to get new papers for the motorcycle or to buy oil and have it serviced so that it can run. I’m asking you to give me a hand so I can work and keep fighting for the beautiful family that father God has given me. With my motorcycle I can help a lot. I can help my daughters and drive them to their classes at college. I ask you with all my heart and promise that one day in life before I leave this world I will be so grateful to all of you. I’m hoping for your support for this great man that at one time made mistakes and committed a crime and paid for it in jail, but now is better, changed and improved, doing everything right that he can.",
                    "When I was little I lived with my mother, where the only thing I received was her abuse and the abuse of my father. They hit me a lot and treated me very badly. I watched how my father hit my mother and I without being able to do anything because I was little. The abuse was so bad from my parents that at six years old I went to live with my grandmother who loved me so much. She treated me so well. She helped me a lot and I started to study. I always wanted to be a merchant marine so I could travel and see the world. I kept going and behaved myself but at fourteen my grandmother passed away and my life fell apart. I was left alone without anyone’s help. At fourteen I entered the world of crime and at almost fifteen I killed my first man. At almost sixteen I killed the other. From there I started my life in the world of crime. It was so bad that when I came of age I was locked up twice in the jail Las Flores de Catia. It was a very dangerous jail, and there I got used to crime and kept getting deeper into that world. It was so bad that in the 90’s I was the second most wanted man in Venezuela. I was in all the newspapers and on TV. The police chief looking for me was named Iván Simonovis and he brought me to justice and I was sentenced to 13 years in prison where I went through eight jails throughout the country. In jail people still respected me and I was in the leadership of a prison gang. I continued to do bad things until one day I found God and he helped me get out of that life. My mother, my stepfather, my wife and my family supported me and visited me in all the jails that I went to. I always had the support of my family in that monster of cement where I learned evil but also learned good things. One night I decided to leave that world in which I was buried. I wanted to leave jail alive and achieved that thanks to God. I got out on the 16th of September, the day of Our Lady of Mercy, and also my wife Yamilet Zapata’s birthday. Finally I escaped that labyrinth where men feed themselves with the blood of living beings. Thanks to God I left that jail with my life.",
                    "After getting out of jail on September 16th, I arrived at my new home and started a new life. I left the world of drugs where I was buried for years. I’ve been out of the world of drugs and crime for 17 years. I started to work and get ahead to give a good life and education to my two daughters. I know that I was a bad person, but I want my daughters to be different than their father; educated and prepared women. Today I feel very blessed by God because my daughter, at 17 years old, has started to study at the Central University of Venezuela because she is a very good student. My younger daughter is 16 and in her senior year of high school. She graduates this year and is a very good student. My daughters have gotten ahead. I have taught them the right values that no one ever taught me. I am very proud of my family, of my daughters and my wife. I am a changed and tenacious man; I was able to get ahead and feel that I’m doing very well. I feel very good right now without being a criminal and without taking drugs: I feel very thankful to God and my family for supporting me all these years that I was buried in the world of crime. Here you have a new Vladimir, improved and moving forward. Many thanks to those who have supported me and those who have believed in my rehabilitation.",
                    "At 46 years old I feel very good because these days I work for the rights of those deprived of their freedom. Now I help people that find themselves in that world. It is never too late. A few months ago I applied for a program online to get my high school diploma and was selected. God always gives good opportunities. I will keep fighting and growing each day. A big hug with all my heart to all of you for believing in me and my family. God bless you."
                ],
                "sp": ["hi"]
            }
        }
    },
    {
        "cam":{
            "name": "vladimir",
            "category":"nutrition",
            "campaignName":"Mototaxista Vladimir",
            "author": "Vladimir",
            "authorInitial": "V",
            "target":200,
            "title":{
                "en":"Help Vladimir Work As a Mototaxista",
                "sp":"Ayuda Vladimir trabajar Mototaxista"
                },
            "description":{
                "en": "Help Vladimir get back on his feet after his motorcycle was stolen",
                "sp": "Help Vladimir get back on his feet after his motorcycle was stolen but in spanish"
            },
            "date": "12/12/2020",
            "image": require('../../../pics/vlad1.jpg'),
            "images": [
                require('../../../pics/vlad2.jpg'),
                require('../../../pics/vlad3.jpg'),
                require('../../../pics/vlad4.jpg'),
            ],
            "headers": {
                "en":[
                    "Vladimir’s Story",
                    "Where I’ve come from…",
                    "Who I am today…",
                    "Where I’m going…"
                ],
                "sp":[
                    "La historia de vladimir",
                    "De dónde vengo",
                    "Quien soy hoy en día",
                    "Hacia dónde voy"
                ]
            },
            "story": {
                "en":[
                    "I’ve gotten it together since I got out of jail. I used to have everything I wanted but it was wrongfully obtained. I decided to work and fight to be able to have what I do starting over again on the right path. I have a disability in one leg and have always had a motorcycle that I use to support my family. In January someone stole it from me and I was left without any way of making money to support my family. We spent many nights going to bed hungry for up to two days at a time because I didn’t have food or money to feed them. I had good people that gave me a hand with the food, but what I really want is to work and keep fighting for my family. God watches over me and never abandons me. A few days ago a friend gifted me a new motorcycle that was his, but the papers were lost and he gave it to me so that I could work and help my family, but right now I haven’t been able to work because I don’t have the money to get new papers for the motorcycle or to buy oil and have it serviced so that it can run. I’m asking you to give me a hand so I can work and keep fighting for the beautiful family that father God has given me. With my motorcycle I can help a lot. I can help my daughters and drive them to their classes at college. I ask you with all my heart and promise that one day in life before I leave this world I will be so grateful to all of you. I’m hoping for your support for this great man that at one time made mistakes and committed a crime and paid for it in jail, but now is better, changed and improved, doing everything right that he can.",
                    "When I was little I lived with my mother, where the only thing I received was her abuse and the abuse of my father. They hit me a lot and treated me very badly. I watched how my father hit my mother and I without being able to do anything because I was little. The abuse was so bad from my parents that at six years old I went to live with my grandmother who loved me so much. She treated me so well. She helped me a lot and I started to study. I always wanted to be a merchant marine so I could travel and see the world. I kept going and behaved myself but at fourteen my grandmother passed away and my life fell apart. I was left alone without anyone’s help. At fourteen I entered the world of crime and at almost fifteen I killed my first man. At almost sixteen I killed the other. From there I started my life in the world of crime. It was so bad that when I came of age I was locked up twice in the jail Las Flores de Catia. It was a very dangerous jail, and there I got used to crime and kept getting deeper into that world. It was so bad that in the 90’s I was the second most wanted man in Venezuela. I was in all the newspapers and on TV. The police chief looking for me was named Iván Simonovis and he brought me to justice and I was sentenced to 13 years in prison where I went through eight jails throughout the country. In jail people still respected me and I was in the leadership of a prison gang. I continued to do bad things until one day I found God and he helped me get out of that life. My mother, my stepfather, my wife and my family supported me and visited me in all the jails that I went to. I always had the support of my family in that monster of cement where I learned evil but also learned good things. One night I decided to leave that world in which I was buried. I wanted to leave jail alive and achieved that thanks to God. I got out on the 16th of September, the day of Our Lady of Mercy, and also my wife Yamilet Zapata’s birthday. Finally I escaped that labyrinth where men feed themselves with the blood of living beings. Thanks to God I left that jail with my life.",
                    "After getting out of jail on September 16th, I arrived at my new home and started a new life. I left the world of drugs where I was buried for years. I’ve been out of the world of drugs and crime for 17 years. I started to work and get ahead to give a good life and education to my two daughters. I know that I was a bad person, but I want my daughters to be different than their father; educated and prepared women. Today I feel very blessed by God because my daughter, at 17 years old, has started to study at the Central University of Venezuela because she is a very good student. My younger daughter is 16 and in her senior year of high school. She graduates this year and is a very good student. My daughters have gotten ahead. I have taught them the right values that no one ever taught me. I am very proud of my family, of my daughters and my wife. I am a changed and tenacious man; I was able to get ahead and feel that I’m doing very well. I feel very good right now without being a criminal and without taking drugs: I feel very thankful to God and my family for supporting me all these years that I was buried in the world of crime. Here you have a new Vladimir, improved and moving forward. Many thanks to those who have supported me and those who have believed in my rehabilitation.",
                    "At 46 years old I feel very good because these days I work for the rights of those deprived of their freedom. Now I help people that find themselves in that world. It is never too late. A few months ago I applied for a program online to get my high school diploma and was selected. God always gives good opportunities. I will keep fighting and growing each day. A big hug with all my heart to all of you for believing in me and my family. God bless you."
                ],
                "sp": [
                    "Yo he salido adelante desde que salí de la cárcel. Antes tenía todo lo que yo quería pero era mal habido, pero yo decidí trabajar y luchar para poder tener mis cosas echándole pichón a la vida por el buen camino. Yo tengo una discapacidad en una pierna y bueno siempre he tenido moto y he trabajado con mi moto que es el sustento de mi familia. En enero me robaron la moto y quedé sin ninguna entrada de dinero para poder ayudar a mi familia, duramos muchas veces acostándonos sin comer hasta dos días porque no tenía alimentos ni dinero para poder darle alimentos a mi familia. Si conseguí buenas personas que me echaban una mano para los alimentos, pero yo lo que quiero es trabajar y seguir luchando por mi familia. Dios siempre va por delante y nunca me abandona. Hace varios días un amigo me regaló una moto que era de él, pero se le perdieron los papeles y él me la dió para que yo trabajara y ayude a mi familia, pero en este momento no he podido trabajar porque no tengo el dinero para sacarle los papeles a mi moto ni tengo para comprarle el aceite y hacerle el servicio que se lleva la moto. Se los pido de todo corazón, mi gente, que me echen una mano para trabajar y seguir luchando por la familia tan linda y bella que me dió papá Dios. Yo con mi moto me puedo ayudar mucho y ayudar a mis hijas y llevarlas a la universidad, se los pido de todo corazón y les prometo que alguna vez en la vida antes de yo parta de este mundo se los voy agradecer toda la vida y espero su aporte a este gran hombre que en algún momento cometió errores y cometió un delito y los pagó con cárcel, pero ahora está bien, cambiado y renovado, haciendo todo lo bueno.",
                    "Desde pequeño vivía con mi madre, donde lo único que recibí fue su maltrato y el de mi padre. Me golpeaban mucho y me trataban muy mal. Yo veía como mi padre golpeaba a mi madre y yo sin poder hacer nada porque era pequeño. Fue tanto el maltrato que recibí de mis padres que a  los 6 años me fuí a vivir con mi abuela que tanto me amó. Ella me trataba muy bien, me ayudó mucho y empecé a estudiar. Yo  siempre quise ser un marino mercante para viajar y conocer  partes del mundo. Yo seguía adelante y me portaba muy bien pero a la edad de los 14 años mi abuela falleció y mi vida se derrumbó.  Quedé solo sin apoyo de nadie. A la edad de los 14 años empecé en el mundo de la delincuencia y ya casi cumpliendo los 15 años maté al primer hombre y ya casi a los 16 años mate al otro. De ahí empezó mi vida en el mundo de la delincuencia. Fue tanto así que cuando cumplí la mayoría de edad estuve preso en dos oportunidades en la  cárcel Las Flores de Catia.  Era una cárcel muy peligrosa, y ahí me gradué de delincuente y seguí sonando en el mundo de la delincuencia. Fue tanto así que en los años 90 fuí el segundo hombre más buscado de Venezuela. Salía en todos los periódicos y en las noticias en la televisión. El comisario que me buscaba era Iván Simonovis, y bueno me puse a derecho con la justicia y fui condenado  a 13 años de prisión donde recorrí 8 cárceles del país. En la cárcel aún me seguían respetando y estuve jugando en el carro de los pranes como líder y ahí seguí haciendo lo malo, hasta que un día conocí a Dios y él me ayudó a salir de esa vida. Mi madre, mi padrastro, mi esposa y mis dos hijas  me apoyaban y me visitaban a todas la cárceles que era trasladado. Siempre tuve el apoyo de mi familia en ese monstruo de cemento donde aprendí lo malo y también aprendí cosas buenas. Una noche decidí salirme de ese mundo donde estaba sumergido y yo quería salir vivo de la cárcel y lo logré gracias a Dios. Salí un 16 de septiembre,  el día de las Mercedes y día del preso y también es el día que mi esposa Yamilet Zapata cumple años. Al fin salí de ese laberinto donde el humano se alimenta de sangre de seres vivos. Gracias a Dios  logré salir vivo de esa cárcel.",
                    "Desde que salí de la cárcel aquel 16 de septiembre, llegué a mi nuevo hogar y empecé una nueva vida. Dejé el mundo de las drogas donde estuve sumergido muchos años. Ya tengo 17 años que salí del mundo de las drogas y del mundo de la delincuencia, empecé a trabajar y a surgir para salir adelante y darle una buena vida y educación a mis dos hijas. Yo sé que yo era una persona mala, pero yo quería que mis hijas fueran diferentes a su papá; mujeres estudiadas y preparadas. Hoy en día me siento bendecido por Dios porque mi hija a los 17 años entró a estudiar en la Universidad Central de Venezuela, por ser muy buena estudiante. Mi hija pequeña tiene 16 años y está en quinto año de bachillerato.  Este año se gradúa y es muy buena estudiante. Mis hijas han salido adelante. Yo les he enseñado los buenos valores que a mi nunca me enseñaron. Me siento muy orgulloso de mi familia, de mis hijas y de mi esposa.Yo soy un hombre cambiado y luchador; logré salir adelante y siento que lo estoy haciendo muy bien. Me siento muy bien ahora sin ser un delincuente y sin consumir drogas: Me siento muy agradecido con Dios y mi familia por apoyarme tantos años que estuve sumergido en el mundo de la delincuencia. Aquí tienen a un Vladimir nuevo y renovado y echado p’alante. Muchas gracias a los que me han apoyado y los que han creído en mi reinserción social.",
                    "Ya a la edad de 46 años me siento muy bien porque hoy en día trabajo por los derechos de los privados de libertad. Ahora ayudo a la gente que se encuentra en ese mundo, pero nunca es tarde. Hace unos meses me postulé en un programa privado por internet, para sacar mi bachillerato y salí seleccionado. Siempre Dios le da buenas oportunidades a uno. Seguiré luchando y creciendo cada día más.Un fuerte abrazo de todo corazón a todos ustedes por creer en mí y en mi familia. Dios los bendiga.",
                ]
            }
        },
    },
    {
        "cam":{
            "name": "vladimir",
            "category":"business",
            "campaignName":"Mototaxista Vladimir",
            "author": "Vladimir",
            "authorInitial": "V",
            "target":200,
            "title":{
                "en":"Help Vladimir Work As a Mototaxista",
                "sp":"Ayuda Vladimir trabajar Mototaxista"
                },
            "description":{
                "en": "Help Vladimir get back on his feet after his motorcycle was stolen",
                "sp": "Help Vladimir get back on his feet after his motorcycle was stolen but in spanish"
            },
            "date": "12/12/2020",
            "image": require('../../../pics/vlad1.jpg'),
            "images": [
                require('../../../pics/vlad2.jpg'),
                require('../../../pics/vlad3.jpg'),
                require('../../../pics/vlad4.jpg'),
            ],
            "headers": {
                "en":[
                    "Vladimir’s Story",
                    "Where I’ve come from…",
                    "Who I am today…",
                    "Where I’m going…"
                ],
                "sp":[
                    "La historia de vladimir",
                    "De dónde vengo",
                    "Quien soy hoy en día",
                    "Hacia dónde voy"
                ]
            },
            "story": {
                "en":[
                    "I’ve gotten it together since I got out of jail. I used to have everything I wanted but it was wrongfully obtained. I decided to work and fight to be able to have what I do starting over again on the right path. I have a disability in one leg and have always had a motorcycle that I use to support my family. In January someone stole it from me and I was left without any way of making money to support my family. We spent many nights going to bed hungry for up to two days at a time because I didn’t have food or money to feed them. I had good people that gave me a hand with the food, but what I really want is to work and keep fighting for my family. God watches over me and never abandons me. A few days ago a friend gifted me a new motorcycle that was his, but the papers were lost and he gave it to me so that I could work and help my family, but right now I haven’t been able to work because I don’t have the money to get new papers for the motorcycle or to buy oil and have it serviced so that it can run. I’m asking you to give me a hand so I can work and keep fighting for the beautiful family that father God has given me. With my motorcycle I can help a lot. I can help my daughters and drive them to their classes at college. I ask you with all my heart and promise that one day in life before I leave this world I will be so grateful to all of you. I’m hoping for your support for this great man that at one time made mistakes and committed a crime and paid for it in jail, but now is better, changed and improved, doing everything right that he can.",
                    "When I was little I lived with my mother, where the only thing I received was her abuse and the abuse of my father. They hit me a lot and treated me very badly. I watched how my father hit my mother and I without being able to do anything because I was little. The abuse was so bad from my parents that at six years old I went to live with my grandmother who loved me so much. She treated me so well. She helped me a lot and I started to study. I always wanted to be a merchant marine so I could travel and see the world. I kept going and behaved myself but at fourteen my grandmother passed away and my life fell apart. I was left alone without anyone’s help. At fourteen I entered the world of crime and at almost fifteen I killed my first man. At almost sixteen I killed the other. From there I started my life in the world of crime. It was so bad that when I came of age I was locked up twice in the jail Las Flores de Catia. It was a very dangerous jail, and there I got used to crime and kept getting deeper into that world. It was so bad that in the 90’s I was the second most wanted man in Venezuela. I was in all the newspapers and on TV. The police chief looking for me was named Iván Simonovis and he brought me to justice and I was sentenced to 13 years in prison where I went through eight jails throughout the country. In jail people still respected me and I was in the leadership of a prison gang. I continued to do bad things until one day I found God and he helped me get out of that life. My mother, my stepfather, my wife and my family supported me and visited me in all the jails that I went to. I always had the support of my family in that monster of cement where I learned evil but also learned good things. One night I decided to leave that world in which I was buried. I wanted to leave jail alive and achieved that thanks to God. I got out on the 16th of September, the day of Our Lady of Mercy, and also my wife Yamilet Zapata’s birthday. Finally I escaped that labyrinth where men feed themselves with the blood of living beings. Thanks to God I left that jail with my life.",
                    "After getting out of jail on September 16th, I arrived at my new home and started a new life. I left the world of drugs where I was buried for years. I’ve been out of the world of drugs and crime for 17 years. I started to work and get ahead to give a good life and education to my two daughters. I know that I was a bad person, but I want my daughters to be different than their father; educated and prepared women. Today I feel very blessed by God because my daughter, at 17 years old, has started to study at the Central University of Venezuela because she is a very good student. My younger daughter is 16 and in her senior year of high school. She graduates this year and is a very good student. My daughters have gotten ahead. I have taught them the right values that no one ever taught me. I am very proud of my family, of my daughters and my wife. I am a changed and tenacious man; I was able to get ahead and feel that I’m doing very well. I feel very good right now without being a criminal and without taking drugs: I feel very thankful to God and my family for supporting me all these years that I was buried in the world of crime. Here you have a new Vladimir, improved and moving forward. Many thanks to those who have supported me and those who have believed in my rehabilitation.",
                    "At 46 years old I feel very good because these days I work for the rights of those deprived of their freedom. Now I help people that find themselves in that world. It is never too late. A few months ago I applied for a program online to get my high school diploma and was selected. God always gives good opportunities. I will keep fighting and growing each day. A big hug with all my heart to all of you for believing in me and my family. God bless you."
                ],
                "sp": [
                    "Yo he salido adelante desde que salí de la cárcel. Antes tenía todo lo que yo quería pero era mal habido, pero yo decidí trabajar y luchar para poder tener mis cosas echándole pichón a la vida por el buen camino. Yo tengo una discapacidad en una pierna y bueno siempre he tenido moto y he trabajado con mi moto que es el sustento de mi familia. En enero me robaron la moto y quedé sin ninguna entrada de dinero para poder ayudar a mi familia, duramos muchas veces acostándonos sin comer hasta dos días porque no tenía alimentos ni dinero para poder darle alimentos a mi familia. Si conseguí buenas personas que me echaban una mano para los alimentos, pero yo lo que quiero es trabajar y seguir luchando por mi familia. Dios siempre va por delante y nunca me abandona. Hace varios días un amigo me regaló una moto que era de él, pero se le perdieron los papeles y él me la dió para que yo trabajara y ayude a mi familia, pero en este momento no he podido trabajar porque no tengo el dinero para sacarle los papeles a mi moto ni tengo para comprarle el aceite y hacerle el servicio que se lleva la moto. Se los pido de todo corazón, mi gente, que me echen una mano para trabajar y seguir luchando por la familia tan linda y bella que me dió papá Dios. Yo con mi moto me puedo ayudar mucho y ayudar a mis hijas y llevarlas a la universidad, se los pido de todo corazón y les prometo que alguna vez en la vida antes de yo parta de este mundo se los voy agradecer toda la vida y espero su aporte a este gran hombre que en algún momento cometió errores y cometió un delito y los pagó con cárcel, pero ahora está bien, cambiado y renovado, haciendo todo lo bueno.",
                    "Desde pequeño vivía con mi madre, donde lo único que recibí fue su maltrato y el de mi padre. Me golpeaban mucho y me trataban muy mal. Yo veía como mi padre golpeaba a mi madre y yo sin poder hacer nada porque era pequeño. Fue tanto el maltrato que recibí de mis padres que a  los 6 años me fuí a vivir con mi abuela que tanto me amó. Ella me trataba muy bien, me ayudó mucho y empecé a estudiar. Yo  siempre quise ser un marino mercante para viajar y conocer  partes del mundo. Yo seguía adelante y me portaba muy bien pero a la edad de los 14 años mi abuela falleció y mi vida se derrumbó.  Quedé solo sin apoyo de nadie. A la edad de los 14 años empecé en el mundo de la delincuencia y ya casi cumpliendo los 15 años maté al primer hombre y ya casi a los 16 años mate al otro. De ahí empezó mi vida en el mundo de la delincuencia. Fue tanto así que cuando cumplí la mayoría de edad estuve preso en dos oportunidades en la  cárcel Las Flores de Catia.  Era una cárcel muy peligrosa, y ahí me gradué de delincuente y seguí sonando en el mundo de la delincuencia. Fue tanto así que en los años 90 fuí el segundo hombre más buscado de Venezuela. Salía en todos los periódicos y en las noticias en la televisión. El comisario que me buscaba era Iván Simonovis, y bueno me puse a derecho con la justicia y fui condenado  a 13 años de prisión donde recorrí 8 cárceles del país. En la cárcel aún me seguían respetando y estuve jugando en el carro de los pranes como líder y ahí seguí haciendo lo malo, hasta que un día conocí a Dios y él me ayudó a salir de esa vida. Mi madre, mi padrastro, mi esposa y mis dos hijas  me apoyaban y me visitaban a todas la cárceles que era trasladado. Siempre tuve el apoyo de mi familia en ese monstruo de cemento donde aprendí lo malo y también aprendí cosas buenas. Una noche decidí salirme de ese mundo donde estaba sumergido y yo quería salir vivo de la cárcel y lo logré gracias a Dios. Salí un 16 de septiembre,  el día de las Mercedes y día del preso y también es el día que mi esposa Yamilet Zapata cumple años. Al fin salí de ese laberinto donde el humano se alimenta de sangre de seres vivos. Gracias a Dios  logré salir vivo de esa cárcel.",
                    "Desde que salí de la cárcel aquel 16 de septiembre, llegué a mi nuevo hogar y empecé una nueva vida. Dejé el mundo de las drogas donde estuve sumergido muchos años. Ya tengo 17 años que salí del mundo de las drogas y del mundo de la delincuencia, empecé a trabajar y a surgir para salir adelante y darle una buena vida y educación a mis dos hijas. Yo sé que yo era una persona mala, pero yo quería que mis hijas fueran diferentes a su papá; mujeres estudiadas y preparadas. Hoy en día me siento bendecido por Dios porque mi hija a los 17 años entró a estudiar en la Universidad Central de Venezuela, por ser muy buena estudiante. Mi hija pequeña tiene 16 años y está en quinto año de bachillerato.  Este año se gradúa y es muy buena estudiante. Mis hijas han salido adelante. Yo les he enseñado los buenos valores que a mi nunca me enseñaron. Me siento muy orgulloso de mi familia, de mis hijas y de mi esposa.Yo soy un hombre cambiado y luchador; logré salir adelante y siento que lo estoy haciendo muy bien. Me siento muy bien ahora sin ser un delincuente y sin consumir drogas: Me siento muy agradecido con Dios y mi familia por apoyarme tantos años que estuve sumergido en el mundo de la delincuencia. Aquí tienen a un Vladimir nuevo y renovado y echado p’alante. Muchas gracias a los que me han apoyado y los que han creído en mi reinserción social.",
                    "Ya a la edad de 46 años me siento muy bien porque hoy en día trabajo por los derechos de los privados de libertad. Ahora ayudo a la gente que se encuentra en ese mundo, pero nunca es tarde. Hace unos meses me postulé en un programa privado por internet, para sacar mi bachillerato y salí seleccionado. Siempre Dios le da buenas oportunidades a uno. Seguiré luchando y creciendo cada día más.Un fuerte abrazo de todo corazón a todos ustedes por creer en mí y en mi familia. Dios los bendiga.",
                ]
            }
        },
    }
    
]

export default campaigns;